import { BadRequestException,Body,Controller,Get,NotFoundException,Param,ParseUUIDPipe,Post } from "@nestjs/common";
import { CurrentUser } from "@common/decorators/current-user.decorator";import { Roles } from "@common/decorators/roles.decorator";import { Role } from "@common/enums/role.enum";
import { PaymentMethod } from "../../application/contracts/billing.contracts";import { BillingError,BillingNotFoundError } from "../../application/errors/billing.error";import { AssessFineUseCase,CreatePaymentUseCase,ListReaderFinesUseCase,ListReaderPaymentsUseCase,SimulatePaymentUseCase } from "../../application/use-cases/billing.use-cases";import { CalculateFineDto,CreatePaymentDto,SimulatePaymentDto } from "./dto/billing.dto";
@Controller()export class BillingController{constructor(private assess:AssessFineUseCase,private fines:ListReaderFinesUseCase,private createPayment:CreatePaymentUseCase,private simulatePayment:SimulatePaymentUseCase,private payments:ListReaderPaymentsUseCase){}
 @Roles(Role.STAFF)@Post("fines/calculate")calculate(@Body()b:CalculateFineDto,@CurrentUser()u:any){return this.handle(()=>this.assess.execute({actorId:u.id,loanItemId:b.loanItemId}));}
 @Roles(Role.STAFF,Role.READER)@Get("fines/readers/:readerId")listFines(@Param("readerId",ParseUUIDPipe)id:string,@CurrentUser()u:any){return this.handle(()=>this.fines.execute(id,u.role===Role.READER?u.readerId:undefined));}
 @Roles(Role.STAFF,Role.READER)@Post("payments")create(@Body()b:CreatePaymentDto,@CurrentUser()u:any){return this.handle(()=>{if(u.role===Role.READER&&b.method===PaymentMethod.CASH)throw new BillingError("Cash payment must be recorded by staff");const readerId=u.role===Role.READER?u.readerId:b.readerId;if(!readerId)throw new BillingError("Reader ID is required");return this.createPayment.execute({actorId:u.id,readerId,fineIds:b.fineIds,method:b.method});});}
 @Roles(Role.STAFF)@Post("payments/:id/simulate")simulate(@Param("id",ParseUUIDPipe)id:string,@Body()b:SimulatePaymentDto,@CurrentUser()u:any){return this.handle(()=>this.simulatePayment.execute({actorId:u.id,paymentId:id,result:b.result}));}
 @Roles(Role.STAFF,Role.READER)@Get("payments/readers/:readerId")listPayments(@Param("readerId",ParseUUIDPipe)id:string,@CurrentUser()u:any){return this.handle(()=>this.payments.execute(id,u.role===Role.READER?u.readerId:undefined));}
 private async handle<T>(work:()=>Promise<T>){try{return await work();}catch(e){if(e instanceof BillingNotFoundError)throw new NotFoundException(e.message);if(e instanceof BillingError)throw new BadRequestException(e.message);throw e;}}}
